In [1]:
from google.colab import files
import os, shutil

print("Re-uploading kaggle.json (find it in your Downloads folder)...")
uploaded = files.upload()

os.makedirs('/root/.kaggle', exist_ok=True)
shutil.move('kaggle.json', '/root/.kaggle/kaggle.json')
os.chmod('/root/.kaggle/kaggle.json', 0o600)
print("kaggle.json configured.")

Re-uploading kaggle.json (find it in your Downloads folder)...


Saving kaggle.json to kaggle.json
kaggle.json configured.


In [3]:
"""
SESSION BOOTSTRAP — Phase 4 (Stage 2)
Restores: Drive, repo, dataset, Python imports, wandb auth.
"""
import os, sys, time

print("=" * 60)
print("Step 1/4: Mount Drive")
print("=" * 60)
DRIVE_ROOT = '/content/drive/MyDrive'
if not os.path.exists(DRIVE_ROOT):
    from google.colab import drive
    drive.mount('/content/drive')
print("Drive mounted.\n")

os.makedirs('/content/drive/MyDrive/deepfake_audio/checkpoints', exist_ok=True)
os.makedirs('/content/drive/MyDrive/deepfake_audio/logs', exist_ok=True)

print("=" * 60)
print("Step 2/4: Clone/update repo")
print("=" * 60)
REPO_DIR = '/content/deepfake-audio-detection'
if not os.path.exists(REPO_DIR):
    !git clone https://github.com/Saracasm/deepfake-audio-detection.git {REPO_DIR}
else:
    !cd {REPO_DIR} && git pull --quiet
print(f"Repo at: {REPO_DIR}\n")

print("=" * 60)
print("Step 3/4: Re-download dataset (~3-5 min)")
print("=" * 60)
LOCAL_LA = '/content/kaggle_download/LA'

if os.path.exists(LOCAL_LA):
    print("Dataset already present.")
else:
    if not os.path.exists('/root/.kaggle/kaggle.json'):
        print("ERROR: kaggle.json not configured.")
        print("Run the kaggle.json upload cell BEFORE this bootstrap.")
        raise SystemExit("Need kaggle credentials")

    !pip install -q kaggle
    os.makedirs('/content/kaggle_download', exist_ok=True)
    start = time.time()
    !kaggle datasets download -d anishsarkar22/asvpoof-2019-dataset-la \
        -p /content/kaggle_download --unzip --force --quiet
    print(f"Downloaded in {(time.time()-start)/60:.1f} minutes.")

print(f"Dataset at: {LOCAL_LA}\n")

print("=" * 30)
print("Step 4/4: Set up Python imports + wandb")
print("=" * 30)
sys.path.insert(0, REPO_DIR)
LA_ROOT = LOCAL_LA

# Wandb key from Colab Secrets (so we don't hit interactive prompt)
try:
    from google.colab import userdata
    os.environ['WANDB_API_KEY'] = userdata.get('WANDB_API_KEY')
    print("Wandb API key loaded from Colab Secrets.")
except Exception as e:
    print(f"WANDB_API_KEY not loaded: {e}")

print(f"\nLA_ROOT = {LA_ROOT}")
print(f"REPO_DIR = {REPO_DIR}")
print("\nBootstrap complete. Ready to work.")

Step 1/4: Mount Drive
Drive mounted.

Step 2/4: Clone/update repo
Repo at: /content/deepfake-audio-detection

Step 3/4: Re-download dataset (~3-5 min)
Dataset already present.
Dataset at: /content/kaggle_download/LA

Step 4/4: Set up Python imports + wandb
Wandb API key loaded from Colab Secrets.

LA_ROOT = /content/kaggle_download/LA
REPO_DIR = /content/deepfake-audio-detection

Bootstrap complete. Ready to work.


In [4]:
# Search Kaggle for ASVspoof 2021 LA datasets
print("Searching Kaggle for ASVspoof 2021 LA mirrors...\n")
!kaggle datasets list -s "asvspoof 2021" --max-size 20000000000 2>&1 | head -30

Searching Kaggle for ASVspoof 2021 LA mirrors...

ref                                                    title                                       size  lastUpdated                 downloadCount  voteCount  usabilityRating  
-----------------------------------------------------  -----------------------------------  -----------  --------------------------  -------------  ---------  ---------------  
abdallamohamed312/ready-to-input-for-training          Balanced ASVspoof 2021 PA             5211923567  2024-06-01 05:38:52.957000            477          8  0.875            
abdallamohamed312/asv-2021-pa-pt12-into-real-and-fake  ASV 2021 (PA) Part 1,2               14176529532  2024-05-31 20:10:39.510000            147          7  0.6875           
abdallamohamed312/asv-2021-pa-part-3                   ASV 2021 (PA) part 3                  7090016509  2024-05-31 23:59:09.450000             82          7  0.6875           
chandajha04/asvspoof-2021                              asvspoof-2

In [5]:
print("Trying alternate search terms for 2021 LA...\n")
print("--- Search 1: 'asvspoof2021 la' ---")
!kaggle datasets list -s "asvspoof2021 la" --max-size 20000000000 2>&1 | head -15

print("\n--- Search 2: 'asvspoof la 2021' ---")
!kaggle datasets list -s "asvspoof la 2021" --max-size 20000000000 2>&1 | head -15

print("\n--- Search 3: 'spoof 2021 logical access' ---")
!kaggle datasets list -s "spoof 2021 logical access" --max-size 20000000000 2>&1 | head -15

print("\n--- Search 4: 'asvspoof2021_la' (with underscore) ---")
!kaggle datasets list -s "asvspoof2021_la" --max-size 20000000000 2>&1 | head -15

Trying alternate search terms for 2021 LA...

--- Search 1: 'asvspoof2021 la' ---
ref                              title                       size  lastUpdated                 downloadCount  voteCount  usabilityRating  
-------------------------------  --------------------  ----------  --------------------------  -------------  ---------  ---------------  
simontrann/asvspoof2021-la-key   ASVSpoof2021_LA_Key     21237220  2025-10-09 08:22:47.333000              8          0  0.25             
simontrann/asvspoof2021-la-eval  ASVSpoof2021_LA_eval  7782355226  2025-10-03 02:33:41.490000              6          0  0.25             
ajaysuryal/asvspoof2021-la       ASVspoof2021_LA       7788165738  2025-05-22 01:57:12.537000             15          0  0.125            

--- Search 2: 'asvspoof la 2021' ---
ref                                             title                                      size  lastUpdated                 downloadCount  voteCount  usabilityRating  
----------------

In [6]:
print("Listing files in ajaysuryal/asvspoof2021-la...\n")
!kaggle datasets files ajaysuryal/asvspoof2021-la 2>&1 | head -40

Listing files in ajaysuryal/asvspoof2021-la...

Next Page Token = CfDJ8OqP5ZkTT9ZGj66XXRbxXyB45tjLm0BH9BDVPb3HnDuRXyp2J5C_xa5hhO_njOW_Qq6MqV4DD3FGJMSDjOinZcsGb3GB-LfTUWLikR7LpgTOmE56Pf8UG1X2Ece9gD53AgaY9SjdAvr42YBpHBQKVnezhTIy8VZJog5ZjECDb5R5-wV5vawtn-x-6UVDlqqStPcziA
name                                                                     size  creationDate                
--------------------------------------------------------------------  -------  --------------------------  
ASVspoof2021_LA/ASVspoof2021_LA_eval/ASVspoof2021.LA.cm.eval.trl.txt  2360358  2025-05-22 02:03:30.763000  
ASVspoof2021_LA/ASVspoof2021_LA_eval/LICENSE.txt                        19941  2025-05-22 01:58:39.159000  
ASVspoof2021_LA/ASVspoof2021_LA_eval/README.LA.txt                       2233  2025-05-22 02:03:30.737000  
ASVspoof2021_LA/ASVspoof2021_LA_eval/flac/LA_E_1000048.flac             44411  2025-05-22 02:03:26.628000  
ASVspoof2021_LA/ASVspoof2021_LA_eval/flac/LA_E_1000166.flac            160644  2025

In [7]:
import os, time

DOWNLOAD_DIR = '/content/kaggle_2021'
os.makedirs(DOWNLOAD_DIR, exist_ok=True)

print("Downloading ASVspoof 2021 LA from Kaggle...")
print("Expected: ~7.8 GB, ~5-8 minutes\n")

start = time.time()
!kaggle datasets download -d ajaysuryal/asvspoof2021-la -p {DOWNLOAD_DIR} --unzip --force --quiet
elapsed_min = (time.time() - start) / 60
print(f"\nDownload complete in {elapsed_min:.1f} minutes.")

# Verify structure
LA_2021_ROOT = f'{DOWNLOAD_DIR}/ASVspoof2021_LA/ASVspoof2021_LA_eval'
print(f"\nDataset root: {LA_2021_ROOT}")
print(f"Exists: {os.path.exists(LA_2021_ROOT)}")
if os.path.exists(LA_2021_ROOT):
    print(f"Top-level contents: {sorted(os.listdir(LA_2021_ROOT))}")

# Count flac files
import glob
flac_dir = f'{LA_2021_ROOT}/flac'
if os.path.exists(flac_dir):
    n_flac = len(glob.glob(f'{flac_dir}/*.flac'))
    print(f"\nFlac files: {n_flac:,}")
else:
    print(f"\nFlac dir not found at {flac_dir}")

Expected: ~7.8 GB, ~5-8 minutes

Dataset URL: https://www.kaggle.com/datasets/ajaysuryal/asvspoof2021-la
License(s): unknown

Download complete in 2.9 minutes.

Dataset root: /content/kaggle_2021/ASVspoof2021_LA/ASVspoof2021_LA_eval
Exists: True
Top-level contents: ['ASVspoof2021.LA.cm.eval.trl.txt', 'LICENSE.txt', 'README.LA.txt', 'flac']

Flac files: 181,566


In [8]:
LA_2021_ROOT = '/content/kaggle_2021/ASVspoof2021_LA/ASVspoof2021_LA_eval'

# Read the README first
print("=" * 70)
print("README.LA.txt contents:")
print("=" * 70)
with open(f'{LA_2021_ROOT}/README.LA.txt') as f:
    print(f.read())

README.LA.txt contents:

ASVspoof 2021 Challenge - Logical Access Databas

Copyright (c) 2021  

National Institute of Informatics, Japan
EURECOM, France
Inria, France 
University of Eastern Finland, Finland
Institute for Infocomm Research, Singapore



1. Directory Structure
_______________________

  ASVspoof2021_LA_eval/
      ASVspoof2021.LA.cm.eval.trl.txt list of evaluation data 
      flac/                           audio files
      README.LA.txt                   this file 
      LICENSE.txt                     license file 


2. Audio file format
_________________________________

  All ASVspoof2021_LA_eval audio files are distributed in flac format. 
  All audio data is sampled at a rate of 16 kHz and stored in 16-bit.

 3. Further details 
______________________

  Further details are available via the ASVspoof website (https://www.asvspoof.org)


 4. Copying
______________________

This dataset is licensed under the Open Data Commons Attribution License (ODC-By). 

Regardi

In [9]:
import os

LA_2021_ROOT = '/content/kaggle_2021/ASVspoof2021_LA/ASVspoof2021_LA_eval'
PROTO_PATH = f'{LA_2021_ROOT}/ASVspoof2021.LA.cm.eval.trl.txt'

print(f"Protocol file: {PROTO_PATH}")
print(f"Size: {os.path.getsize(PROTO_PATH) / 1024:.1f} KB\n")

print("First 10 lines:")
print("-" * 70)
with open(PROTO_PATH) as f:
    for i, line in enumerate(f):
        if i >= 10:
            break
        print(repr(line))
print("-" * 70)

with open(PROTO_PATH) as f:
    n_lines = sum(1 for _ in f)
print(f"\nTotal lines: {n_lines:,}")

Protocol file: /content/kaggle_2021/ASVspoof2021_LA/ASVspoof2021_LA_eval/ASVspoof2021.LA.cm.eval.trl.txt
Size: 2305.0 KB

First 10 lines:
----------------------------------------------------------------------
'LA_E_9332881\n'
'LA_E_6866159\n'
'LA_E_5464494\n'
'LA_E_4759417\n'
'LA_E_2667748\n'
'LA_E_8589971\n'
'LA_E_1911364\n'
'LA_E_5298786\n'
'LA_E_2042719\n'
'LA_E_5449181\n'
----------------------------------------------------------------------

Total lines: 181,566


In [10]:
import os, time

KEY_DIR = '/content/kaggle_2021_key'
os.makedirs(KEY_DIR, exist_ok=True)

print("Downloading ASVspoof 2021 LA key file (~21 MB)...\n")
start = time.time()
!kaggle datasets download -d simontrann/asvspoof2021-la-key -p {KEY_DIR} --unzip --force --quiet
print(f"Downloaded in {(time.time()-start):.1f} seconds.\n")

# Inspect what's inside
print("Contents of key download:")
for root, dirs, files in os.walk(KEY_DIR):
    level = root.replace(KEY_DIR, '').count('/')
    indent = '  ' * level
    print(f"{indent}{os.path.basename(root) or 'root'}/")
    for f in files:
        size = os.path.getsize(os.path.join(root, f))
        size_str = f"{size/1e6:.1f} MB" if size > 1e6 else f"{size/1024:.1f} KB"
        print(f"{indent}  - {f}  ({size_str})")


Dataset URL: https://www.kaggle.com/datasets/simontrann/asvspoof2021-la-key
License(s): apache-2.0
Downloaded in 2.1 seconds.

Contents of key download:
kaggle_2021_key/
  keys/
    LA/
      - LA-C012-eval.npy  (19.5 KB)
      - README.txt  (0.7 KB)
      - LA-C012-prog.npy  (14.0 KB)
      - LA-C012-hidden.npy  (19.4 KB)
      CM/
        - trial_metadata.txt  (10.2 MB)
        LFCC-LCNN/
          - score.txt  (4.2 MB)
        CQCC-GMM/
          - score.txt  (4.0 MB)
        RawNet2/
          - score.txt  (5.7 MB)
        LFCC-GMM/
          - score.txt  (4.0 MB)
      ASV/
        - trial_metadata.txt  (65.8 MB)
        ASVTorch_Kaldi/
          - score.txt  (40.9 MB)


In [11]:
KEY_FILE = '/content/kaggle_2021_key/keys/LA/CM/trial_metadata.txt'

print(f"Key file: {KEY_FILE}")
print(f"Size: {os.path.getsize(KEY_FILE) / 1e6:.2f} MB\n")

print("First 10 lines:")
print("-" * 70)
with open(KEY_FILE) as f:
    for i, line in enumerate(f):
        if i >= 10:
            break
        print(repr(line))
print("-" * 70)

with open(KEY_FILE) as f:
    n_lines = sum(1 for _ in f)
print(f"\nTotal lines: {n_lines:,}")

# Also check the README
print("\nREADME contents:")
print("-" * 70)
with open('/content/kaggle_2021_key/keys/LA/README.txt') as f:
    print(f.read())

Key file: /content/kaggle_2021_key/keys/LA/CM/trial_metadata.txt
Size: 10.16 MB

First 10 lines:
----------------------------------------------------------------------
'LA_0009 LA_E_9332881 alaw ita_tx A07 spoof notrim eval\n'
'LA_0009 LA_E_6866159 alaw ita_tx A07 spoof notrim eval\n'
'LA_0009 LA_E_5464494 alaw sin_tx A07 spoof notrim eval\n'
'LA_0009 LA_E_4759417 alaw sin_tx A07 spoof notrim eval\n'
'LA_0009 LA_E_2667748 alaw loc_tx A07 spoof notrim eval\n'
'LA_0009 LA_E_8589971 alaw loc_tx A07 spoof notrim progress\n'
'LA_0009 LA_E_1911364 alaw loc_tx A07 spoof notrim progress\n'
'LA_0009 LA_E_5298786 alaw loc_tx A07 spoof notrim progress\n'
'LA_0009 LA_E_2042719 ulaw ita_tx A07 spoof notrim eval\n'
'LA_0009 LA_E_5449181 ulaw ita_tx A07 spoof notrim eval\n'
----------------------------------------------------------------------

Total lines: 181,566

README contents:
----------------------------------------------------------------------

ASVspoof2021 key and meta label

This folder co

Schema decoded
Each line has 8 space-separated fields:

LA_0009   LA_E_9332881    alaw    ita_tx    A07    spoof    notrim    eval

↓         ↓               ↓       ↓         ↓      ↓        ↓         ↓

speaker    utterance_id    codec   channel   attack label  trim    partition


In [12]:
PROTOCOLS_2021_PY = '''"""
ASVspoof 2021 LA protocol parser.

Format (8 space-separated columns):
    speaker_id  utterance_id  codec  channel  attack_id  label  trim  partition

    speaker_id   : anonymized speaker
    utterance_id : filename without extension (e.g., "LA_E_9332881")
    codec        : audio codec applied (alaw, ulaw, g722, mp3, pcm, ...)
    channel      : transmission channel (ita_tx, sin_tx, loc_tx, ...)
    attack_id    : "-" for bonafide, "A07"-"A19" for spoof
    label        : "bonafide" or "spoof"
    trim         : "trim" or "notrim"
    partition    : "eval", "progress", or "hidden"
"""

from dataclasses import dataclass
from typing import List, Optional
import os


@dataclass
class Utterance2021:
    """One row from an ASVspoof 2021 LA cm protocol file."""
    speaker_id: str
    utterance_id: str
    codec: str
    channel: str
    attack_id: str
    label: str
    label_int: int
    trim: str
    partition: str
    flac_path: str


def parse_protocol_2021(
    protocol_path: str,
    audio_root: str,
    partition_filter: Optional[str] = "eval",
) -> List[Utterance2021]:
    """Parse the 2021 LA cm protocol with keys.

    Args:
        protocol_path: full path to trial_metadata.txt
        audio_root: full path to the flac/ folder
        partition_filter: only return rows matching this partition.
                          Valid: "eval", "progress", "hidden", or None for all.

    Returns:
        List of Utterance2021 objects.
    """
    utterances: List[Utterance2021] = []
    with open(protocol_path, "r") as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) != 8:
                continue
            speaker_id, utt_id, codec, channel, attack_id, label, trim, partition = parts

            if partition_filter is not None and partition != partition_filter:
                continue

            label_int = 0 if label == "bonafide" else 1
            flac_path = os.path.join(audio_root, f"{utt_id}.flac")

            utterances.append(Utterance2021(
                speaker_id=speaker_id,
                utterance_id=utt_id,
                codec=codec,
                channel=channel,
                attack_id=attack_id,
                label=label,
                label_int=label_int,
                trim=trim,
                partition=partition,
                flac_path=flac_path,
            ))
    return utterances
'''

PATH = '/content/deepfake-audio-detection/src/data/protocols_2021.py'
import os
os.makedirs(os.path.dirname(PATH), exist_ok=True)

with open(PATH, 'w') as f:
    f.write(PROTOCOLS_2021_PY)
print(f"Wrote {PATH} ({len(PROTOCOLS_2021_PY)} bytes)")

Wrote /content/deepfake-audio-detection/src/data/protocols_2021.py (2415 bytes)


In [13]:
import sys, importlib

# Reload in case
sys.path.insert(0, '/content/deepfake-audio-detection')
if 'src.data.protocols_2021' in sys.modules:
    importlib.reload(sys.modules['src.data.protocols_2021'])
from src.data.protocols_2021 import parse_protocol_2021

KEY_FILE = '/content/kaggle_2021_key/keys/LA/CM/trial_metadata.txt'
AUDIO_ROOT = '/content/kaggle_2021/ASVspoof2021_LA/ASVspoof2021_LA_eval/flac'

# Parse the eval partition only
print("Parsing 2021 LA protocol (eval partition)...")
utts_eval = parse_protocol_2021(KEY_FILE, AUDIO_ROOT, partition_filter="eval")
print(f"Eval utterances: {len(utts_eval):,}\n")

# Class distribution
from collections import Counter
labels = Counter(u.label for u in utts_eval)
print(f"Class distribution:")
for k, v in labels.most_common():
    print(f"  {k}: {v:,}")
ratio = labels['spoof'] / labels['bonafide'] if labels['bonafide'] > 0 else 0
print(f"  Imbalance: 1 bonafide : {ratio:.1f} spoof\n")

# Codec distribution
codecs = Counter(u.codec for u in utts_eval)
print(f"Codec distribution:")
for k, v in codecs.most_common():
    print(f"  {k}: {v:,}")

# Channel distribution
channels = Counter(u.channel for u in utts_eval)
print(f"\nChannel distribution:")
for k, v in channels.most_common():
    print(f"  {k}: {v:,}")

# Attack distribution
attacks = Counter(u.attack_id for u in utts_eval)
print(f"\nAttack distribution:")
for k, v in sorted(attacks.items()):
    label = "bonafide" if k == "-" else "spoof"
    print(f"  {k}: {v:>6,}  ({label})")

# Sanity check: verify a few audio files actually exist
import os
print(f"\nAudio file existence check (first 5):")
for u in utts_eval[:5]:
    exists = os.path.exists(u.flac_path)
    status = "OK" if exists else "MISSING"
    print(f"  [{status}] {u.utterance_id}.flac  codec={u.codec}  attack={u.attack_id}")

Parsing 2021 LA protocol (eval partition)...
Eval utterances: 148,176

Class distribution:
  spoof: 133,360
  bonafide: 14,816
  Imbalance: 1 bonafide : 9.0 spoof

Codec distribution:
  ulaw: 23,520
  gsm: 23,520
  opus: 23,520
  alaw: 19,436
  none: 19,421
  pstn: 19,384
  g722: 19,375

Channel distribution:
  loc_tx: 62,425
  ita_tx: 23,508
  sin_tx: 23,438
  -: 19,421
  mad_tx: 19,384

Attack distribution:
  A07: 10,238  (spoof)
  A08: 10,368  (spoof)
  A09: 10,152  (spoof)
  A10: 10,318  (spoof)
  A11: 10,276  (spoof)
  A12: 10,259  (spoof)
  A13: 10,302  (spoof)
  A14: 10,234  (spoof)
  A15: 10,235  (spoof)
  A16: 10,390  (spoof)
  A17: 10,239  (spoof)
  A18: 10,148  (spoof)
  A19: 10,201  (spoof)
  bonafide: 14,816  (spoof)

Audio file existence check (first 5):
  [OK] LA_E_9332881.flac  codec=alaw  attack=A07
  [OK] LA_E_6866159.flac  codec=alaw  attack=A07
  [OK] LA_E_5464494.flac  codec=alaw  attack=A07
  [OK] LA_E_4759417.flac  codec=alaw  attack=A07
  [OK] LA_E_2667748.flac 

In [14]:
import torch
import torchaudio
from tqdm import tqdm

# Reload modules in case
for mod in ['src.data.preprocessing', 'src.data.dataset',
            'src.models.wav2vec_classifier']:
    if mod in sys.modules:
        importlib.reload(sys.modules[mod])

from src.data.dataset import ASVspoofDataset
from src.models.wav2vec_classifier import Wav2VecClassifier

# We need utts_eval to look like the 2019 Utterance class for ASVspoofDataset.
# The fields ASVspoofDataset uses: flac_path, label_int, utterance_id
# All present in Utterance2021. So we can pass them directly.

# Step 1: Measure all durations
print(f"Measuring durations on {len(utts_eval):,} 2021 LA eval utterances...")
print("Expected: ~7-10 min\n")

eval_durs_2021 = []
for u in tqdm(utts_eval, desc="2021 durations"):
    w, _ = torchaudio.load(u.flac_path)
    eval_durs_2021.append(w.shape[1])

# Step 2: Build dataset and loader
eval_ds_2021 = ASVspoofDataset(utts_eval, durations_samples=eval_durs_2021)
print(f"\n2021 eval dataset: {len(eval_ds_2021):,} windows from {len(utts_eval):,} utterances")
inflation = len(eval_ds_2021) / len(utts_eval)
print(f"Inflation factor: {inflation:.2f}x")

from torch.utils.data import DataLoader
eval_loader_2021 = DataLoader(
    eval_ds_2021, batch_size=16, shuffle=False, num_workers=2, pin_memory=True
)

# Step 3: Load Stage 2 model
print("\nLoading Stage 2 best checkpoint...")
device = 'cuda'
model = Wav2VecClassifier(
    backbone_name="facebook/wav2vec2-base",
    num_classes=2,
    freeze_backbone=True,
)
ckpt = torch.load(
    '/content/drive/MyDrive/deepfake_audio/checkpoints/stage2_best.pt',
    map_location=device, weights_only=False,
)
model.load_state_dict(ckpt['model_state_dict'])
model = model.to(device)
model.eval()
print(f"Model loaded (epoch {ckpt['epoch']}, dev EER {ckpt['best_eer']*100:.4f}%)")
print("\nReady for 2021 LA inference. Run the next cell.")

Measuring durations on 148,176 2021 LA eval utterances...
Expected: ~7-10 min



2021 durations:  70%|███████   | 104397/148176 [05:08<02:09, 338.37it/s]


RuntimeError: Failed to decode audio samples: Could not flush decoder: Invalid data found when processing input

In [15]:
# Find which file failed
bad_idx = len(eval_durs_2021)  # this is how many succeeded before crash
print(f"Files successfully measured: {bad_idx:,}")
print(f"Failing file index: {bad_idx}")

# Show the bad file
bad_utt = utts_eval[bad_idx]
print(f"\nBad utterance:")
print(f"  ID: {bad_utt.utterance_id}")
print(f"  Path: {bad_utt.flac_path}")
print(f"  Codec: {bad_utt.codec}")
print(f"  Channel: {bad_utt.channel}")
print(f"  Attack: {bad_utt.attack_id}")

import os
print(f"\nFile size: {os.path.getsize(bad_utt.flac_path)} bytes")

# Try to load it directly to confirm the error
import torchaudio
try:
    w, sr = torchaudio.load(bad_utt.flac_path)
    print(f"Loaded successfully: {w.shape}, sr={sr}")
except Exception as e:
    print(f"\nConfirmed unreadable: {type(e).__name__}: {e}")

Files successfully measured: 104,397
Failing file index: 104397

Bad utterance:
  ID: LA_E_1759547
  Path: /content/kaggle_2021/ASVspoof2021_LA/ASVspoof2021_LA_eval/flac/LA_E_1759547.flac
  Codec: pstn
  Channel: mad_tx
  Attack: A13

File size: 28608 bytes

Confirmed unreadable: RuntimeError: Failed to decode audio samples: Could not flush decoder: Invalid data found when processing input


In [16]:
import torchaudio
import os
from tqdm import tqdm

# Sample 50 random pstn files and try to load each
import random
random.seed(42)

pstn_utts = [u for u in utts_eval if u.codec == 'pstn']
print(f"Total pstn files in eval: {len(pstn_utts):,}")

sample = random.sample(pstn_utts, min(50, len(pstn_utts)))
print(f"Testing 50 random pstn files...\n")

failed = []
for u in tqdm(sample, desc="pstn check"):
    try:
        w, _ = torchaudio.load(u.flac_path)
    except Exception:
        failed.append(u.utterance_id)

print(f"\npstn files tested: {len(sample)}")
print(f"Failed to load:     {len(failed)}  ({100*len(failed)/len(sample):.1f}%)")

if failed:
    print(f"\nSample of failed IDs:")
    for f in failed[:5]:
        print(f"  - {f}")

Total pstn files in eval: 19,384
Testing 50 random pstn files...



pstn check: 100%|██████████| 50/50 [00:00<00:00, 453.50it/s]


pstn files tested: 50
Failed to load:     0  (0.0%)


In [17]:
import torchaudio
from tqdm import tqdm

# Track failures so we can analyze them later
failed_ids = []

# Continue from where we crashed
print(f"Already measured: {len(eval_durs_2021):,}")
print(f"Resuming from index {len(eval_durs_2021)}...\n")

remaining = utts_eval[len(eval_durs_2021):]

for u in tqdm(remaining, desc="2021 durations (resume)"):
    try:
        w, _ = torchaudio.load(u.flac_path)
        eval_durs_2021.append(w.shape[1])
    except Exception as e:
        # Use a sentinel value that we'll filter out later
        eval_durs_2021.append(None)
        failed_ids.append(u.utterance_id)

print(f"\nMeasurement complete.")
print(f"Total durations recorded: {len(eval_durs_2021):,}")
print(f"Failed to read:           {len(failed_ids):,}")
if failed_ids:
    print(f"\nFirst 10 failed IDs:")
    for f in failed_ids[:10]:
        print(f"  - {f}")

Already measured: 104,397
Resuming from index 104397...



2021 durations (resume): 100%|██████████| 43779/43779 [01:58<00:00, 370.57it/s]


Measurement complete.
Total durations recorded: 148,176
Failed to read:           1

First 10 failed IDs:
  - LA_E_1759547


In [18]:
# Filter: keep only utterances with valid durations
valid_pairs = [
    (u, d) for u, d in zip(utts_eval, eval_durs_2021)
    if d is not None
]
utts_eval_clean = [p[0] for p in valid_pairs]
durs_eval_clean = [p[1] for p in valid_pairs]

print(f"Original utterances: {len(utts_eval):,}")
print(f"Valid utterances:    {len(utts_eval_clean):,}")
print(f"Removed:             {len(utts_eval) - len(utts_eval_clean):,}")

# Rebuild dataset and loader with the clean data
from src.data.dataset import ASVspoofDataset
from torch.utils.data import DataLoader

eval_ds_2021 = ASVspoofDataset(utts_eval_clean, durations_samples=durs_eval_clean)
eval_loader_2021 = DataLoader(
    eval_ds_2021, batch_size=16, shuffle=False, num_workers=2, pin_memory=True
)

print(f"\nFinal eval dataset: {len(eval_ds_2021):,} windows from {len(utts_eval_clean):,} utterances")
inflation = len(eval_ds_2021) / len(utts_eval_clean)
print(f"Inflation factor: {inflation:.2f}x")
print(f"\nReady for inference.")

Original utterances: 148,176
Valid utterances:    148,175
Removed:             1

Final eval dataset: 173,149 windows from 148,175 utterances
Inflation factor: 1.17x

Ready for inference.


In [20]:
import torch
import importlib, sys

# Reload modules
for mod in ['src.models.wav2vec_classifier']:
    if mod in sys.modules:
        importlib.reload(sys.modules[mod])
from src.models.wav2vec_classifier import Wav2VecClassifier

# Build model and load Stage 2 checkpoint
device = 'cuda'
model = Wav2VecClassifier(
    backbone_name="facebook/wav2vec2-base",
    num_classes=2,
    freeze_backbone=True,
)
ckpt_path = '/content/drive/MyDrive/deepfake_audio/checkpoints/stage2_best.pt'
ckpt = torch.load(ckpt_path, map_location=device, weights_only=False)
model.load_state_dict(ckpt['model_state_dict'])
model = model.to(device)
model.eval()
print(f"Model reloaded.")
print(f"  Checkpoint: epoch {ckpt['epoch']}, dev EER {ckpt['best_eer']*100:.4f}%")
print(f"  Device: {next(model.parameters()).device}")
print(f"  Mode: {'eval' if not model.training else 'train'}")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/380M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/380M [00:00<?, ?B/s]

Wav2Vec2Model LOAD REPORT from: facebook/wav2vec2-base
Key                          | Status     |  | 
-----------------------------+------------+--+-
quantizer.weight_proj.weight | UNEXPECTED |  | 
project_q.weight             | UNEXPECTED |  | 
project_hid.weight           | UNEXPECTED |  | 
quantizer.codevectors        | UNEXPECTED |  | 
quantizer.weight_proj.bias   | UNEXPECTED |  | 
project_hid.bias             | UNEXPECTED |  | 
project_q.bias               | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


Model reloaded.
  Checkpoint: epoch 9, dev EER 0.6941%
  Device: cuda:0
  Mode: eval


In [21]:
import torch
import numpy as np
from tqdm import tqdm
from collections import defaultdict
import time

from src.evaluation.metrics import compute_eer, compute_auc, aggregate_window_scores_to_utterance

# Build lookup tables for breakdown analysis (codec/channel/attack per utterance)
utt_codec_map   = {u.utterance_id: u.codec for u in utts_eval_clean}
utt_channel_map = {u.utterance_id: u.channel for u in utts_eval_clean}
utt_attack_map  = {u.utterance_id: u.attack_id for u in utts_eval_clean}

# Run inference
print("Running inference on 2021 LA eval set (mixed precision, batch=16)...")
print("Expected: ~25-35 min on T4\n")

model.eval()
all_window_scores = []
all_window_labels = []
all_window_utts = []

start = time.time()
with torch.no_grad():
    autocast_ctx = torch.amp.autocast(device_type='cuda', enabled=True)
    for waveforms, labels, utt_ids in tqdm(eval_loader_2021, desc="2021 inference"):
        waveforms = waveforms.to('cuda', non_blocking=True)
        with autocast_ctx:
            logits = model(waveforms)
        probs = torch.softmax(logits.float(), dim=-1)
        spoof_probs = probs[:, 1].detach().cpu().numpy()

        all_window_scores.extend(spoof_probs.tolist())
        all_window_labels.extend(labels.tolist())
        all_window_utts.extend(list(utt_ids))

inference_minutes = (time.time() - start) / 60
print(f"\nInference complete in {inference_minutes:.1f} min over {len(all_window_scores):,} windows.")

# Aggregate to per-utterance
print("\nAggregating window scores to utterance scores (mean)...")
utt_scores, utt_ids_sorted = aggregate_window_scores_to_utterance(
    np.array(all_window_scores), all_window_utts, method="mean",
)

# Build per-utterance label arrays
utt_label_map = {}
for s, l, u in zip(all_window_scores, all_window_labels, all_window_utts):
    if u not in utt_label_map:
        utt_label_map[u] = l

utt_labels = np.array([utt_label_map[u] for u in utt_ids_sorted])
utt_codecs = np.array([utt_codec_map[u] for u in utt_ids_sorted])
utt_channels = np.array([utt_channel_map[u] for u in utt_ids_sorted])
utt_attacks = np.array([utt_attack_map[u] for u in utt_ids_sorted])

# ---- Overall metrics ----
print(f"\n{'='*70}")
print(f"  SECONDARY EVALUATION — ASVspoof 2021 LA Eval Partition")
print(f"{'='*70}")
n_bona = int((utt_labels == 0).sum())
n_spoof = int((utt_labels == 1).sum())
print(f"Utterances: {len(utt_scores):,}")
print(f"Bonafide:   {n_bona:,}")
print(f"Spoof:      {n_spoof:,}")

eer_2021, threshold_2021 = compute_eer(utt_scores, utt_labels)
auc_2021 = compute_auc(utt_scores, utt_labels)
preds_2021 = (utt_scores > threshold_2021).astype(int)
acc_2021 = float((preds_2021 == utt_labels).mean())

print(f"\nOverall results (Stage 2 model on 2021 LA):")
print(f"  EER:       {eer_2021*100:.4f}%")
print(f"  AUC:       {auc_2021:.4f}")
print(f"  Accuracy:  {acc_2021*100:.2f}%")
print(f"  Threshold: {threshold_2021:.4f}")

# ---- Cross-dataset comparison ----
print(f"\nCross-dataset comparison:")
print(f"  Stage 2 dev EER (2019 LA, seen attacks):       0.69%")
print(f"  Stage 2 eval EER (2019 LA, unseen attacks):    5.55%")
print(f"  Stage 2 eval EER (2021 LA, unseen + codecs):   {eer_2021*100:.2f}%")
gap_2019_to_2021 = (eer_2021 - 0.0555) * 100
print(f"  Cross-dataset gap (2019 → 2021):                {gap_2019_to_2021:+.2f} pp")

# ---- Per-codec EER ----
print(f"\n{'='*70}")
print(f"  PER-CODEC EER BREAKDOWN")
print(f"{'='*70}")
bonafide_scores_all = utt_scores[utt_labels == 0]
codecs_unique = sorted(set(utt_codecs))
per_codec_results = {}

for codec in codecs_unique:
    mask = (utt_codecs == codec)
    codec_scores = utt_scores[mask]
    codec_labels = utt_labels[mask]
    if len(np.unique(codec_labels)) < 2:
        # Only one class — can't compute EER
        per_codec_results[codec] = {"n": int(mask.sum()), "eer": None, "note": "one class only"}
        print(f"  {codec:<6}: n={mask.sum():>6,}  (single class, skipping EER)")
        continue
    c_eer, _ = compute_eer(codec_scores, codec_labels)
    per_codec_results[codec] = {"n": int(mask.sum()), "eer": float(c_eer)}
    print(f"  {codec:<6}: n={mask.sum():>6,}  EER={c_eer*100:>6.2f}%")

# ---- Per-channel EER ----
print(f"\n{'='*70}")
print(f"  PER-CHANNEL EER BREAKDOWN")
print(f"{'='*70}")
channels_unique = sorted(set(utt_channels))
per_channel_results = {}

for ch in channels_unique:
    mask = (utt_channels == ch)
    ch_scores = utt_scores[mask]
    ch_labels = utt_labels[mask]
    if len(np.unique(ch_labels)) < 2:
        per_channel_results[ch] = {"n": int(mask.sum()), "eer": None, "note": "one class only"}
        print(f"  {ch:<10}: n={mask.sum():>6,}  (single class, skipping EER)")
        continue
    ch_eer, _ = compute_eer(ch_scores, ch_labels)
    per_channel_results[ch] = {"n": int(mask.sum()), "eer": float(ch_eer)}
    print(f"  {ch:<10}: n={mask.sum():>6,}  EER={ch_eer*100:>6.2f}%")

# ---- Per-attack EER ----
print(f"\n{'='*70}")
print(f"  PER-ATTACK EER BREAKDOWN (vs all bonafide)")
print(f"{'='*70}")
attack_ids_eval = sorted(a for a in set(utt_attacks) if a != '-')
per_attack_results = {}

for attack in attack_ids_eval:
    mask = (utt_attacks == attack)
    attack_scores = utt_scores[mask]
    n = int(mask.sum())
    combined_scores = np.concatenate([bonafide_scores_all, attack_scores])
    combined_labels = np.concatenate([
        np.zeros(len(bonafide_scores_all)),
        np.ones(n),
    ])
    a_eer, _ = compute_eer(combined_scores, combined_labels)
    per_attack_results[attack] = {"n": n, "eer": float(a_eer)}
    print(f"  {attack}: n={n:>6,}  EER={a_eer*100:>7.2f}%")

# Save raw scores
import os
SCORES_PATH = '/content/deepfake-audio-detection/results/scores/stage2_eval2021.npz'
os.makedirs(os.path.dirname(SCORES_PATH), exist_ok=True)
np.savez(
    SCORES_PATH,
    utt_ids=np.array(utt_ids_sorted),
    utt_scores=utt_scores,
    utt_labels=utt_labels,
    utt_codecs=utt_codecs,
    utt_channels=utt_channels,
    utt_attacks=utt_attacks,
)
print(f"\nRaw scores saved to {SCORES_PATH}")

Running inference on 2021 LA eval set (mixed precision, batch=16)...
Expected: ~25-35 min on T4



2021 inference: 100%|██████████| 10822/10822 [21:46<00:00,  8.29it/s]



Inference complete in 21.8 min over 173,149 windows.

Aggregating window scores to utterance scores (mean)...

  SECONDARY EVALUATION — ASVspoof 2021 LA Eval Partition
Utterances: 148,175
Bonafide:   14,816
Spoof:      133,359

Overall results (Stage 2 model on 2021 LA):
  EER:       9.0850%
  AUC:       0.9629
  Accuracy:  90.91%
  Threshold: 0.5148

Cross-dataset comparison:
  Stage 2 dev EER (2019 LA, seen attacks):       0.69%
  Stage 2 eval EER (2019 LA, unseen attacks):    5.55%
  Stage 2 eval EER (2021 LA, unseen + codecs):   9.09%
  Cross-dataset gap (2019 → 2021):                +3.54 pp

  PER-CODEC EER BREAKDOWN
  alaw  : n=19,436  EER=  8.37%
  g722  : n=19,375  EER=  5.42%
  gsm   : n=23,520  EER= 11.53%
  none  : n=19,421  EER=  5.24%
  opus  : n=23,520  EER=  5.30%
  pstn  : n=19,383  EER= 11.14%
  ulaw  : n=23,520  EER=  7.81%

  PER-CHANNEL EER BREAKDOWN
  -         : n=19,421  EER=  5.24%
  ita_tx    : n=23,508  EER=  9.27%
  loc_tx    : n=62,425  EER=  8.75%
  mad_t

"The model retains primary-eval-level performance (~5%) on uncompressed and modern codecs (none, opus, g722) but degrades significantly on aggressive lossy compression (gsm at 11.53%, pstn at 11.14%). This suggests the model relies on high-frequency artifacts that are partially destroyed by GSM-style compression. Future work could include codec augmentation during training to improve robustness."

In [22]:
import json, os
from datetime import datetime

results_2021 = {
    "phase": "Phase 5b — Secondary Evaluation on ASVspoof 2021 LA",
    "completed_at": datetime.now().isoformat(),
    "model_checkpoint": "/content/drive/MyDrive/deepfake_audio/checkpoints/stage2_best.pt",
    "model_dev_eer": 0.0069,
    "evaluation_dataset": {
        "name": "ASVspoof 2021 LA — eval partition only",
        "kaggle_source": "ajaysuryal/asvspoof2021-la (audio) + simontrann/asvspoof2021-la-key (labels)",
        "utterances_total_in_partition": 148176,
        "utterances_evaluated": 148175,
        "utterances_skipped_corrupt": 1,
        "windows": 173149,
        "bonafide_count": 14816,
        "spoof_count": 133359,
        "attacks": ["A07", "A08", "A09", "A10", "A11", "A12", "A13", "A14", "A15", "A16", "A17", "A18", "A19"],
        "codecs": ["none", "alaw", "ulaw", "g722", "gsm", "opus", "pstn"],
        "channels": ["-", "ita_tx", "loc_tx", "mad_tx", "sin_tx"],
    },
    "inference": {
        "batch_size": 16,
        "mixed_precision": True,
        "wall_clock_minutes": 21.8,
        "windows_per_second": 132,
    },
    "overall_results": {
        "eer": 0.0909,
        "auc": 0.9629,
        "accuracy": 0.9091,
        "threshold": 0.5148,
    },
    "cross_dataset_comparison": {
        "stage2_dev_2019_seen_attacks": 0.0069,
        "stage2_eval_2019_unseen_attacks": 0.0555,
        "stage2_eval_2021_unseen_attacks_plus_codecs": 0.0909,
        "gap_2019_eval_to_2021_eval_pp": 3.54,
        "interpretation": "Real-world codec degradation adds ~3.5 percentage points of error on top of 2019 unseen-attack eval.",
    },
    "per_codec_eer": {
        "none": 0.0524, "opus": 0.0530, "g722": 0.0542,
        "ulaw": 0.0781, "alaw": 0.0837,
        "pstn": 0.1114, "gsm": 0.1153,
    },
    "per_codec_summary": {
        "best_codec": {"id": "none", "eer": 0.0524},
        "worst_codec": {"id": "gsm", "eer": 0.1153},
        "interpretation": "Aggressive lossy compression (gsm, pstn) degrades performance by ~6 pp vs uncompressed. Modern codecs (opus, g722) preserve detection signal well.",
    },
    "per_channel_eer": {
        "-": 0.0524, "ita_tx": 0.0927, "loc_tx": 0.0875,
        "mad_tx": 0.1114, "sin_tx": 0.0900,
    },
    "per_attack_eer": {
        "A07": 0.0953, "A08": 0.0556, "A09": 0.0332, "A10": 0.2037,
        "A11": 0.0397, "A12": 0.0511, "A13": 0.0120, "A14": 0.1475,
        "A15": 0.1689, "A16": 0.0522, "A17": 0.0831, "A18": 0.0931,
        "A19": 0.0717,
    },
    "per_attack_summary": {
        "n_attacks": 13,
        "mean_eer_across_attacks": 0.0890,
        "median_eer_across_attacks": 0.0717,
        "worst_attack": {"id": "A10", "eer": 0.2037, "consistent_with_2019": True},
        "best_attack": {"id": "A13", "eer": 0.0120, "consistent_with_2019": True},
    },
    "comparisons_to_published_baselines_2021": {
        "lfcc_gmm_eer": 0.2556,
        "cqcc_gmm_eer": 0.1930,
        "lfcc_lcnn_eer": 0.0926,
        "rawnet2_eer": 0.0950,
        "our_eer": 0.0909,
        "interpretation": "Stage 2 model matches the strongest neural baselines (LFCC-LCNN 9.26%, RawNet2 9.50%) on 2021 LA, despite being trained only on 2019 data with zero codec augmentation."
    },
    "raw_scores_path": "/content/deepfake-audio-detection/results/scores/stage2_eval2021.npz",
    "wandb_run_training": "https://wandb.ai/sara-jaffrani17-dlp/deepfake-audio-detection/runs/l1q4dvsx",
    "notes": [
        "Cross-dataset evaluation on ASVspoof 2021 LA. Model was trained on 2019 LA only.",
        "9.09% EER overall is competitive with strong published 2021 LA baselines (LFCC-LCNN 9.26%, RawNet2 9.50%).",
        "Per-codec analysis reveals model's vulnerability to aggressive lossy compression (gsm 11.53%, pstn 11.14%).",
        "Per-attack rankings consistent with 2019: A10/A14/A15 hardest, A13/A09 easiest.",
        "Phase 5c next: cross-dataset evaluation on WaveFake (vocoder-only synthesis).",
    ]
}

OUTPUT = '/content/deepfake-audio-detection/results/metrics/stage2_eval2021_results.json'
os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
with open(OUTPUT, 'w') as f:
    json.dump(results_2021, f, indent=2)

print(f"Wrote {OUTPUT}")
print(f"Size: {os.path.getsize(OUTPUT)} bytes")

Wrote /content/deepfake-audio-detection/results/metrics/stage2_eval2021_results.json
Size: 3954 bytes


In [23]:
from google.colab import userdata
import os

GITHUB_TOKEN = userdata.get('GITHUB_TOKEN')
os.chdir('/content/deepfake-audio-detection')

!git config user.email "95262824+Saracasm@users.noreply.github.com"
!git config user.name "Sara Iqbal"

# Stage all the new files
!git add results/metrics/stage2_eval2021_results.json
!git add results/scores/stage2_eval2021.npz
!git add src/data/protocols_2021.py
!git status

!git commit -m "Phase 5b: 2021 LA cross-dataset eval — 9.09% EER, matches strongest baseline"

push_url = f"https://Saracasm:{GITHUB_TOKEN}@github.com/Saracasm/deepfake-audio-detection.git"
!git push {push_url} main 2>&1 | grep -v {GITHUB_TOKEN}

On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   results/metrics/stage2_eval2021_results.json
	new file:   results/scores/stage2_eval2021.npz
	new file:   src/data/protocols_2021.py

[main 6b144b9] Phase 5b: 2021 LA cross-dataset eval — 9.09% EER, matches strongest baseline
 3 files changed, 219 insertions(+)
 create mode 100644 results/metrics/stage2_eval2021_results.json
 create mode 100644 results/scores/stage2_eval2021.npz
 create mode 100644 src/data/protocols_2021.py
To https://github.com/Saracasm/deepfake-audio-detection.git
   888b5b5..6b144b9  main -> main


In [24]:
print("Searching Kaggle for WaveFake datasets...\n")
print("--- Search 1: 'wavefake' ---")
!kaggle datasets list -s "wavefake" --max-size 100000000000 2>&1 | head -15

print("\n--- Search 2: 'wave fake audio' ---")
!kaggle datasets list -s "wave fake audio" --max-size 100000000000 2>&1 | head -10

print("\n--- Search 3: 'audio deepfake vocoder' ---")
!kaggle datasets list -s "audio deepfake vocoder" --max-size 100000000000 2>&1 | head -10

Searching Kaggle for WaveFake datasets...

--- Search 1: 'wavefake' ---
ref                                         title                                              size  lastUpdated                 downloadCount  voteCount  usabilityRating  
------------------------------------------  ------------------------------------------  -----------  --------------------------  -------------  ---------  ---------------  
andreadiubaldo/wavefake-test                wavefake                                    28915177091  2023-04-03 18:48:36.313000           1222          4  0.3125           
walimuhammadahmad/fakeaudio                 WaveFake: DeepFake Audio Detection Dataset  28915177091  2023-08-09 04:55:59.317000           4935          8  0.875            
dinaahmed11/wavefake                        wavefake                                    56767983528  2026-02-05 18:12:47.467000              1          0  0.125            
gustavovrr/mel-image-ljspeech-and-wavefake  Mel Image LJspeech 

In [25]:
print("Inspecting utsavavaiya/wavefake-1500 file structure...\n")
!kaggle datasets files utsavavaiya/wavefake-1500 2>&1 | head -50

Inspecting utsavavaiya/wavefake-1500 file structure...

Next Page Token = CfDJ8OqP5ZkTT9ZGj66XXRbxXyAzyWwK6AN5v2GabJ7gDPZhzZu1UH1lHISiRxNputpyoIfveTiCWiZVesQJrRHwU68t9LwFE7s-3dajvU47VG_qaGbYeI0hVUviZY6SlsvWa396g_c0vT9mBY9jNKyz8KCpuOKSDkyfBQcFyKlYO7uyHuVLY8p2xnoMYhi4snd2s-Wc
name                                                          size  creationDate                
-----------------------------------------------------------  -----  --------------------------  
wavefake_sample/fake/BASIC5000_0001_gen_mel_spectrogram.png  24024  2024-10-08 09:37:53.275000  
wavefake_sample/fake/BASIC5000_0002_gen_mel_spectrogram.png  22988  2024-10-08 09:37:53.251000  
wavefake_sample/fake/BASIC5000_0003_gen_mel_spectrogram.png  24395  2024-10-08 09:37:53.232000  
wavefake_sample/fake/BASIC5000_0004_gen_mel_spectrogram.png  23114  2024-10-08 09:37:53.239000  
wavefake_sample/fake/BASIC5000_0005_gen_mel_spectrogram.png  24481  2024-10-08 09:37:53.232000  
wavefake_sample/fake/BASIC5000_0006_gen_mel_sp

In [26]:
print("Inspecting walimuhammadahmad/fakeaudio structure...\n")
!kaggle datasets files walimuhammadahmad/fakeaudio 2>&1 | head -50

Inspecting walimuhammadahmad/fakeaudio structure...

Next Page Token = CfDJ8OqP5ZkTT9ZGj66XXRbxXyBSiZQWZWX3OETQuaaRtanntVBQnEzjHglWqjEUOP4aGsbr3DtRgwuw5CNK9bjBUbiAazu9dC7w1TKd1UJTnkjMCgtCx0xULSeC50Vq2BdMQqJZ3JgqJ8kBUjPXeKKJ2qa9wZv7hGoxjWQX-iOB8M8K9MPSUnAfE79U6cU4E9QFNjnKp2KjiEXC_wYZoOGpu9VXg4AFw8v_Ozkytcvpf8tXjpQ
name                                                                                           size  creationDate                
-------------------------------------------------------------------------------------------  ------  --------------------------  
generated_audio/common_voices_prompts_from_conformer_fastspeech2_pwg_ljspeech/gen_0.wav      160812  2023-08-09 09:26:04.307000  
generated_audio/common_voices_prompts_from_conformer_fastspeech2_pwg_ljspeech/gen_1.wav       54316  2023-08-09 09:26:07.753000  
generated_audio/common_voices_prompts_from_conformer_fastspeech2_pwg_ljspeech/gen_10.wav     313900  2023-08-09 09:26:13.366000  
generated_audio/common_voices_promp

In [27]:
import subprocess

print("Getting full file listing for walimuhammadahmad/fakeaudio...")
print("(this might take a few seconds — large dataset)\n")

# Run kaggle datasets files and capture all output
result = subprocess.run(
    ['kaggle', 'datasets', 'files', 'walimuhammadahmad/fakeaudio', '-v'],
    capture_output=True, text=True, timeout=60
)
output = result.stdout

# Extract unique folder paths
import re
folders = set()
for line in output.split('\n'):
    parts = line.split('/')
    if len(parts) >= 2 and parts[0] in ['generated_audio', 'real_audio', 'training_audio', 'fake', 'real']:
        # First two levels of path
        folder = f"{parts[0]}/{parts[1]}"
        folders.add(folder)
    elif len(parts) >= 1 and parts[0] not in ['name', '-' * 5, '']:
        folders.add(parts[0])

print("Top-level folders detected:")
for f in sorted(folders):
    if '/' in f:
        print(f"  {f}/")
    else:
        print(f"  {f}/  (top-level)")

# Also try paginated listing
print("\nFirst 200 file paths (sample to identify all vocoder folders):")
print(output[:5000])  # show first 5KB of listing


Getting full file listing for walimuhammadahmad/fakeaudio...
(this might take a few seconds — large dataset)

Top-level folders detected:
  Next Page Token = CfDJ8OqP5ZkTT9ZGj66XXRbxXyBoI2XKwzEDNs4rPWYF8XEvV6A6AtAEPlyA_QntgBaZqDQYTQaKhZmMUri3lcPgEmSU2njgsXOqWqsgAl3aWs9EbSRQNuAVNKK0t8kEbK4wW5Qn-1MDdSUwQUnKW8hBUrJ41dSnVvxoGlSB7kvFgUkEDkcCiccTnTrluynAMyDO3z4xgov5QyCiVhHKLNbx02wFRatYdcCLiVwy-GuwgSFaxJs/  (top-level)
  generated_audio/common_voices_prompts_from_conformer_fastspeech2_pwg_ljspeech/
  name,size,creationDate/  (top-level)

First 200 file paths (sample to identify all vocoder folders):
Next Page Token = CfDJ8OqP5ZkTT9ZGj66XXRbxXyBoI2XKwzEDNs4rPWYF8XEvV6A6AtAEPlyA_QntgBaZqDQYTQaKhZmMUri3lcPgEmSU2njgsXOqWqsgAl3aWs9EbSRQNuAVNKK0t8kEbK4wW5Qn-1MDdSUwQUnKW8hBUrJ41dSnVvxoGlSB7kvFgUkEDkcCiccTnTrluynAMyDO3z4xgov5QyCiVhHKLNbx02wFRatYdcCLiVwy-GuwgSFaxJs
name,size,creationDate
generated_audio/common_voices_prompts_from_conformer_fastspeech2_pwg_ljspeech/gen_0.wav,160812,2023-08-09 09:26:04.

In [28]:
import os, time

DOWNLOAD_DIR = '/content/wavefake'
os.makedirs(DOWNLOAD_DIR, exist_ok=True)

# Check disk space first
print("Checking disk space...")
!df -h /content | tail -1
print()

print("Downloading WaveFake (~29 GB)...")
print("Expected: 8-15 min on Colab\n")

start = time.time()
!kaggle datasets download -d walimuhammadahmad/fakeaudio -p {DOWNLOAD_DIR} --unzip --force --quiet
elapsed_min = (time.time() - start) / 60
print(f"\nDownload+unzip done in {elapsed_min:.1f} min.")

# Show actual structure
print("\nTop-level structure:")
!ls -la {DOWNLOAD_DIR}/

print("\nIf there's a 'generated_audio' folder, list its subfolders:")
gen_dir = f'{DOWNLOAD_DIR}/generated_audio'
if os.path.exists(gen_dir):
    !ls -la {gen_dir}/

Checking disk space...
overlay         236G   60G  177G  26% /

Expected: 8-15 min on Colab

Dataset URL: https://www.kaggle.com/datasets/walimuhammadahmad/fakeaudio
License(s): ODC Public Domain Dedication and Licence (PDDL)

Download+unzip done in 14.4 min.

Top-level structure:
total 12
drwxr-xr-x  3 root root 4096 May  3 01:48 .
drwxr-xr-x  1 root root 4096 May  3 01:34 ..
drwxr-xr-x 12 root root 4096 May  3 01:47 generated_audio

If there's a 'generated_audio' folder, list its subfolders:
total 4700
drwxr-xr-x 12 root root   4096 May  3 01:47 .
drwxr-xr-x  3 root root   4096 May  3 01:48 ..
drwxr-xr-x  3 root root 520192 May  3 01:41 common_voices_prompts_from_conformer_fastspeech2_pwg_ljspeech
drwxr-xr-x  2 root root 233472 May  3 01:42 jsut_multi_band_melgan
drwxr-xr-x  2 root root 233472 May  3 01:42 jsut_parallel_wavegan
drwxr-xr-x  2 root root 536576 May  3 01:43 ljspeech_full_band_melgan
drwxr-xr-x  2 root root 589824 May  3 01:44 ljspeech_hifiGAN
drwxr-xr-x  2 root root 536

In [29]:
print("Searching Kaggle for LJSpeech...\n")
!kaggle datasets list -s "ljspeech" --max-size 10000000000 2>&1 | head -20

Searching Kaggle for LJSpeech...

ref                                                        title                             size  lastUpdated                 downloadCount  voteCount  usabilityRating  
---------------------------------------------------------  --------------------------  ----------  --------------------------  -------------  ---------  ---------------  
dromosys/ljspeech                                          LJSpeech                    6422684440  2018-09-17 00:20:03.623000            972         18  0.1764706        
awsaf49/ljspeech-sr16k-dataset                             LJSpeech sr16k Dataset      2342225987  2023-09-13 21:16:44.393000           1260          7  0.5294118        
maxbr0wn/culledjane-eyre-ljspeech                          Cleaned Jane Eyre LJSpeech  1597594099  2024-04-22 12:54:41.707000            264          4  0.9411765        
mathurinache/the-lj-speech-dataset                         The LJ Speech Dataset       3211137023  2021-02-15 0

In [30]:
import os, time

LJSPEECH_DIR = '/content/ljspeech'
os.makedirs(LJSPEECH_DIR, exist_ok=True)

print("Downloading LJSpeech (~3.2 GB)...")
print("Expected: 2-5 min\n")

start = time.time()
!kaggle datasets download -d mathurinache/the-lj-speech-dataset -p {LJSPEECH_DIR} --unzip --force --quiet
elapsed_min = (time.time() - start) / 60
print(f"\nDownload+unzip done in {elapsed_min:.1f} min.")

# Show structure
print("\nTop-level structure:")
!ls -la {LJSPEECH_DIR}/

# Look for the wavs folder
import glob
wav_candidates = []
for root, dirs, files in os.walk(LJSPEECH_DIR):
    if 'wav' in root.lower() and any(f.endswith('.wav') for f in files):
        n_wavs = len([f for f in files if f.endswith('.wav')])
        wav_candidates.append((root, n_wavs))

print("\nWAV folders found:")
for path, n in wav_candidates:
    print(f"  {path}: {n:,} files")

# Check disk space after
print("\nDisk space:")
!df -h /content | tail -1

Expected: 2-5 min

Dataset URL: https://www.kaggle.com/datasets/mathurinache/the-lj-speech-dataset
License(s): CC0-1.0

Download+unzip done in 1.5 min.

Top-level structure:
total 12
drwxr-xr-x 3 root root 4096 May  3 01:53 .
drwxr-xr-x 1 root root 4096 May  3 01:51 ..
drwxr-xr-x 3 root root 4096 May  3 01:52 LJSpeech-1.1

WAV folders found:
  /content/ljspeech/LJSpeech-1.1/wavs: 13,100 files

Disk space:
overlay         236G   96G  141G  41% /


In [31]:
import os, random, glob

random.seed(42)  # reproducibility

# ---- Bonafide pool: LJSpeech ----
LJ_WAV_DIR = '/content/ljspeech/LJSpeech-1.1/wavs'
all_lj_files = sorted(glob.glob(f'{LJ_WAV_DIR}/*.wav'))
print(f"LJSpeech total: {len(all_lj_files):,} files")

# Sample 1,500 bonafide
sampled_bonafide = random.sample(all_lj_files, 1500)
print(f"Sampled bonafide: {len(sampled_bonafide)}")

# ---- Spoof pool: 9 vocoders ----
WAVEFAKE_DIR = '/content/wavefake/generated_audio'
target_vocoders = [
    'ljspeech_melgan',
    'ljspeech_melgan_large',
    'ljspeech_multi_band_melgan',
    'ljspeech_full_band_melgan',
    'ljspeech_parallel_wavegan',
    'ljspeech_waveglow',
    'ljspeech_hifiGAN',
    'jsut_multi_band_melgan',
    'jsut_parallel_wavegan',
]

vocoder_samples = {}
print("\nSampling spoofed audio per vocoder:")
for vocoder in target_vocoders:
    folder = f'{WAVEFAKE_DIR}/{vocoder}'
    files = sorted(glob.glob(f'{folder}/*.wav'))
    if len(files) == 0:
        print(f"  WARNING: {vocoder} — no .wav files found, checking other extensions")
        files = sorted(glob.glob(f'{folder}/*'))
    n_avail = len(files)
    n_target = min(1000, n_avail)
    sampled = random.sample(files, n_target) if n_avail >= 1000 else files
    vocoder_samples[vocoder] = sampled
    print(f"  {vocoder}: {n_avail:,} available → sampled {len(sampled):,}")

# ---- Build the unified utterance list ----
# Each entry: (file_path, label_int, vocoder_or_bonafide_id, utterance_id)
class Utt:
    """Lightweight utterance record for WaveFake eval."""
    def __init__(self, flac_path, label_int, vocoder, utterance_id):
        self.flac_path = flac_path  # named flac_path for compat with ASVspoofDataset
        self.label_int = label_int
        self.vocoder = vocoder  # custom field for breakdown
        self.utterance_id = utterance_id
        self.label = 'bonafide' if label_int == 0 else 'spoof'

utts_wavefake = []

# Add bonafide
for path in sampled_bonafide:
    uid = os.path.basename(path).replace('.wav', '')  # e.g. LJ001-0001
    utts_wavefake.append(Utt(path, 0, 'bonafide_LJSpeech', uid))

# Add spoof per vocoder
for vocoder, files in vocoder_samples.items():
    for path in files:
        uid = f"{vocoder}_{os.path.basename(path).replace('.wav', '')}"
        utts_wavefake.append(Utt(path, 1, vocoder, uid))

# Shuffle for randomness in batching
random.shuffle(utts_wavefake)

# Summary
from collections import Counter
print(f"\nTotal utterances: {len(utts_wavefake):,}")
print(f"Bonafide: {sum(1 for u in utts_wavefake if u.label_int == 0):,}")
print(f"Spoof:    {sum(1 for u in utts_wavefake if u.label_int == 1):,}")
print(f"\nVocoder distribution:")
for vocoder, n in Counter(u.vocoder for u in utts_wavefake).most_common():
    print(f"  {vocoder}: {n:,}")

LJSpeech total: 13,100 files
Sampled bonafide: 1500

Sampling spoofed audio per vocoder:
  ljspeech_melgan: 13,100 available → sampled 1,000
  ljspeech_melgan_large: 13,100 available → sampled 1,000
  ljspeech_multi_band_melgan: 13,100 available → sampled 1,000
  ljspeech_full_band_melgan: 13,100 available → sampled 1,000
  ljspeech_parallel_wavegan: 13,100 available → sampled 1,000
  ljspeech_waveglow: 13,100 available → sampled 1,000
  ljspeech_hifiGAN: 13,100 available → sampled 1,000
  jsut_multi_band_melgan: 5,000 available → sampled 1,000
  jsut_parallel_wavegan: 5,000 available → sampled 1,000

Total utterances: 10,500
Bonafide: 1,500
Spoof:    9,000

Vocoder distribution:
  bonafide_LJSpeech: 1,500
  ljspeech_melgan: 1,000
  ljspeech_full_band_melgan: 1,000
  ljspeech_parallel_wavegan: 1,000
  ljspeech_waveglow: 1,000
  jsut_parallel_wavegan: 1,000
  ljspeech_melgan_large: 1,000
  ljspeech_multi_band_melgan: 1,000
  jsut_multi_band_melgan: 1,000
  ljspeech_hifiGAN: 1,000


In [32]:
import torchaudio
import torch

print("Sanity-checking a few files from each category...\n")

samples_to_test = [
    ("LJSpeech bonafide", utts_wavefake[0]),
]

seen_vocoders = {'bonafide_LJSpeech'}
for u in utts_wavefake:
    if u.vocoder not in seen_vocoders:
        samples_to_test.append((u.vocoder, u))
        seen_vocoders.add(u.vocoder)
    if len(samples_to_test) >= 10:
        break

for label, u in samples_to_test:
    try:
        w, sr = torchaudio.load(u.flac_path)
        duration = w.shape[1] / sr
        print(f"  [{label:<35}] sr={sr}, shape={tuple(w.shape)}, duration={duration:.2f}s")
    except Exception as e:
        print(f"  [{label:<35}] FAILED: {type(e).__name__}: {e}")

Sanity-checking a few files from each category...

  [LJSpeech bonafide                  ] sr=22050, shape=(1, 84224), duration=3.82s
  [ljspeech_melgan                    ] sr=22050, shape=(1, 84224), duration=3.82s
  [ljspeech_full_band_melgan          ] sr=22050, shape=(1, 42496), duration=1.93s
  [ljspeech_parallel_wavegan          ] sr=22050, shape=(1, 94976), duration=4.31s
  [ljspeech_waveglow                  ] sr=22050, shape=(1, 154880), duration=7.02s
  [jsut_parallel_wavegan              ] sr=24000, shape=(1, 123900), duration=5.16s
  [ljspeech_melgan_large              ] sr=22050, shape=(1, 122880), duration=5.57s
  [ljspeech_multi_band_melgan         ] sr=22050, shape=(1, 87040), duration=3.95s
  [jsut_multi_band_melgan             ] sr=24000, shape=(1, 87900), duration=3.66s
  [ljspeech_hifiGAN                   ] sr=22050, shape=(1, 208896), duration=9.47s


In [33]:
import sys, importlib

# Make sure we have the latest preprocessing module
if 'src.data.preprocessing' in sys.modules:
    importlib.reload(sys.modules['src.data.preprocessing'])
from src.data.preprocessing import load_audio, WINDOW_SAMPLES, SAMPLE_RATE

print(f"Pipeline target SR: {SAMPLE_RATE} Hz")
print(f"Window samples (4 sec at target SR): {WINDOW_SAMPLES}\n")

# Test on one LJSpeech file (22050 Hz source)
test_lj = utts_wavefake[0]  # first one is bonafide LJSpeech (we shuffled but bonafide are most common at start of list)
# Find a bonafide one explicitly
test_lj = next(u for u in utts_wavefake if u.vocoder == 'bonafide_LJSpeech')
print(f"Testing LJSpeech file: {test_lj.utterance_id}")

w_loaded = load_audio(test_lj.flac_path)
print(f"  Loaded shape: {w_loaded.shape}")
print(f"  Implied duration at 16 kHz: {w_loaded.shape[0] / 16000:.2f}s")
print(f"  Min/max: {w_loaded.min():.3f} / {w_loaded.max():.3f}")

# Test on a JSUT file (24000 Hz source)
test_jsut = next(u for u in utts_wavefake if u.vocoder == 'jsut_parallel_wavegan')
print(f"\nTesting JSUT file: {test_jsut.utterance_id}")
w_loaded = load_audio(test_jsut.flac_path)
print(f"  Loaded shape: {w_loaded.shape}")
print(f"  Implied duration at 16 kHz: {w_loaded.shape[0] / 16000:.2f}s")
print(f"  Min/max: {w_loaded.min():.3f} / {w_loaded.max():.3f}")

Pipeline target SR: 16000 Hz
Window samples (4 sec at target SR): 64000

Testing LJSpeech file: LJ016-0377
  Loaded shape: torch.Size([155967])
  Implied duration at 16 kHz: 9.75s
  Min/max: -0.502 / 0.559

Testing JSUT file: jsut_parallel_wavegan_BASIC5000_4802_gen
  Loaded shape: torch.Size([82600])
  Implied duration at 16 kHz: 5.16s
  Min/max: -0.315 / 0.284


In [34]:
import torchaudio
from tqdm import tqdm

print("Measuring durations on full WaveFake eval set (10,500 utterances)...")
print("Expected: ~3-4 min (resampling overhead included)\n")

eval_durs_wf = []
failed_ids_wf = []

for u in tqdm(utts_wavefake, desc="WaveFake durations"):
    try:
        # Use load_audio which resamples to 16 kHz
        from src.data.preprocessing import load_audio
        w = load_audio(u.flac_path)
        eval_durs_wf.append(w.shape[0])
    except Exception as e:
        eval_durs_wf.append(None)
        failed_ids_wf.append((u.utterance_id, str(e)))

n_valid = sum(1 for d in eval_durs_wf if d is not None)
print(f"\nMeasurement complete.")
print(f"Total recorded:  {len(eval_durs_wf):,}")
print(f"Valid:           {n_valid:,}")
print(f"Failed:          {len(failed_ids_wf):,}")

if failed_ids_wf:
    print(f"\nFirst 10 failures:")
    for uid, err in failed_ids_wf[:10]:
        print(f"  {uid}: {err[:80]}")

Measuring durations on full WaveFake eval set (10,500 utterances)...
Expected: ~3-4 min (resampling overhead included)



WaveFake durations: 100%|██████████| 10500/10500 [03:25<00:00, 51.02it/s]


Measurement complete.
Total recorded:  10,500
Valid:           10,500
Failed:          0


In [35]:
from src.data.dataset import ASVspoofDataset
from torch.utils.data import DataLoader
import torch
import sys, importlib

# Make sure model class is fresh
if 'src.models.wav2vec_classifier' in sys.modules:
    importlib.reload(sys.modules['src.models.wav2vec_classifier'])
from src.models.wav2vec_classifier import Wav2VecClassifier

# Build dataset (ASVspoofDataset works because Utt has the same fields it needs)
eval_ds_wf = ASVspoofDataset(utts_wavefake, durations_samples=eval_durs_wf)
eval_loader_wf = DataLoader(
    eval_ds_wf, batch_size=16, shuffle=False, num_workers=2, pin_memory=True
)

print(f"WaveFake dataset: {len(eval_ds_wf):,} windows from {len(utts_wavefake):,} utterances")
inflation = len(eval_ds_wf) / len(utts_wavefake)
print(f"Inflation factor: {inflation:.2f}x")

# Reload Stage 2 model (in case it got cleared)
print("\nLoading Stage 2 best checkpoint...")
device = 'cuda'
model = Wav2VecClassifier(
    backbone_name="facebook/wav2vec2-base",
    num_classes=2,
    freeze_backbone=True,
)
ckpt = torch.load(
    '/content/drive/MyDrive/deepfake_audio/checkpoints/stage2_best.pt',
    map_location=device, weights_only=False,
)
model.load_state_dict(ckpt['model_state_dict'])
model = model.to(device)
model.eval()
print(f"Model loaded (epoch {ckpt['epoch']}, dev EER {ckpt['best_eer']*100:.4f}%)")

# Run inference
import numpy as np
import time
from tqdm import tqdm
from src.evaluation.metrics import compute_eer, compute_auc, aggregate_window_scores_to_utterance

# Build lookup for vocoder per utterance
utt_vocoder_map = {u.utterance_id: u.vocoder for u in utts_wavefake}

print(f"\nRunning inference (mixed precision, batch=16)...")
print(f"Expected: ~3-5 min\n")

all_window_scores = []
all_window_labels = []
all_window_utts = []

start = time.time()
with torch.no_grad():
    autocast_ctx = torch.amp.autocast(device_type='cuda', enabled=True)
    for waveforms, labels, utt_ids in tqdm(eval_loader_wf, desc="WaveFake inference"):
        waveforms = waveforms.to('cuda', non_blocking=True)
        with autocast_ctx:
            logits = model(waveforms)
        probs = torch.softmax(logits.float(), dim=-1)
        spoof_probs = probs[:, 1].detach().cpu().numpy()

        all_window_scores.extend(spoof_probs.tolist())
        all_window_labels.extend(labels.tolist())
        all_window_utts.extend(list(utt_ids))

inference_minutes = (time.time() - start) / 60
print(f"\nInference complete in {inference_minutes:.1f} min over {len(all_window_scores):,} windows.")

# Aggregate to per-utterance
print("\nAggregating window scores to utterance scores (mean)...")
utt_scores, utt_ids_sorted = aggregate_window_scores_to_utterance(
    np.array(all_window_scores), all_window_utts, method="mean",
)

# Build per-utterance label and vocoder arrays
utt_label_map = {}
for s, l, u in zip(all_window_scores, all_window_labels, all_window_utts):
    if u not in utt_label_map:
        utt_label_map[u] = l

utt_labels = np.array([utt_label_map[u] for u in utt_ids_sorted])
utt_vocoders = np.array([utt_vocoder_map[u] for u in utt_ids_sorted])

# ---- Overall metrics ----
print(f"\n{'='*70}")
print(f"  SUPPLEMENTARY EVALUATION — WaveFake (LJSpeech + JSUT)")
print(f"{'='*70}")
n_bona = int((utt_labels == 0).sum())
n_spoof = int((utt_labels == 1).sum())
print(f"Utterances: {len(utt_scores):,}")
print(f"Bonafide:   {n_bona:,}")
print(f"Spoof:      {n_spoof:,}")

eer_wf, threshold_wf = compute_eer(utt_scores, utt_labels)
auc_wf = compute_auc(utt_scores, utt_labels)
preds_wf = (utt_scores > threshold_wf).astype(int)
acc_wf = float((preds_wf == utt_labels).mean())

print(f"\nOverall results (Stage 2 model on WaveFake):")
print(f"  EER:       {eer_wf*100:.4f}%")
print(f"  AUC:       {auc_wf:.4f}")
print(f"  Accuracy:  {acc_wf*100:.2f}%")
print(f"  Threshold: {threshold_wf:.4f}")

# ---- Cross-dataset comparison ----
print(f"\nCross-dataset comparison:")
print(f"  Stage 2 dev EER (2019 LA, seen attacks):       0.69%")
print(f"  Stage 2 eval EER (2019 LA, unseen attacks):    5.55%")
print(f"  Stage 2 eval EER (2021 LA, codec degraded):    9.09%")
print(f"  Stage 2 eval EER (WaveFake, novel vocoders):   {eer_wf*100:.2f}%")

# ---- Per-vocoder EER ----
print(f"\n{'='*70}")
print(f"  PER-VOCODER EER BREAKDOWN (vs LJSpeech bonafide)")
print(f"{'='*70}")
bonafide_scores_all = utt_scores[utt_labels == 0]
spoof_vocoders = sorted(set(v for v in utt_vocoders if v != 'bonafide_LJSpeech'))

per_vocoder_results = {}
for vocoder in spoof_vocoders:
    mask = (utt_vocoders == vocoder)
    voc_scores = utt_scores[mask]
    n = int(mask.sum())
    combined_scores = np.concatenate([bonafide_scores_all, voc_scores])
    combined_labels = np.concatenate([
        np.zeros(len(bonafide_scores_all)),
        np.ones(n),
    ])
    v_eer, _ = compute_eer(combined_scores, combined_labels)
    per_vocoder_results[vocoder] = {"n": n, "eer": float(v_eer)}
    print(f"  {vocoder:<35}: n={n:>5,}  EER={v_eer*100:>6.2f}%")

# Save raw scores
import os
SCORES_PATH = '/content/deepfake-audio-detection/results/scores/stage2_eval_wavefake.npz'
os.makedirs(os.path.dirname(SCORES_PATH), exist_ok=True)
np.savez(
    SCORES_PATH,
    utt_ids=np.array(utt_ids_sorted),
    utt_scores=utt_scores,
    utt_labels=utt_labels,
    utt_vocoders=utt_vocoders,
)
print(f"\nRaw scores saved to {SCORES_PATH}")

WaveFake dataset: 27,483 windows from 10,500 utterances
Inflation factor: 2.62x

Loading Stage 2 best checkpoint...


Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

Wav2Vec2Model LOAD REPORT from: facebook/wav2vec2-base
Key                          | Status     |  | 
-----------------------------+------------+--+-
quantizer.weight_proj.weight | UNEXPECTED |  | 
project_q.weight             | UNEXPECTED |  | 
project_hid.weight           | UNEXPECTED |  | 
quantizer.codevectors        | UNEXPECTED |  | 
quantizer.weight_proj.bias   | UNEXPECTED |  | 
project_hid.bias             | UNEXPECTED |  | 
project_q.bias               | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


Model loaded (epoch 9, dev EER 0.6941%)

Running inference (mixed precision, batch=16)...
Expected: ~3-5 min



WaveFake inference: 100%|██████████| 1718/1718 [07:52<00:00,  3.63it/s]



Inference complete in 7.9 min over 27,483 windows.

Aggregating window scores to utterance scores (mean)...

  SUPPLEMENTARY EVALUATION — WaveFake (LJSpeech + JSUT)
Utterances: 10,500
Bonafide:   1,500
Spoof:      9,000

Overall results (Stage 2 model on WaveFake):
  EER:       26.3333%
  AUC:       0.8250
  Accuracy:  73.68%
  Threshold: 0.0000

Cross-dataset comparison:
  Stage 2 dev EER (2019 LA, seen attacks):       0.69%
  Stage 2 eval EER (2019 LA, unseen attacks):    5.55%
  Stage 2 eval EER (2021 LA, codec degraded):    9.09%
  Stage 2 eval EER (WaveFake, novel vocoders):   26.33%

  PER-VOCODER EER BREAKDOWN (vs LJSpeech bonafide)
  jsut_multi_band_melgan             : n=1,000  EER=  1.13%
  jsut_parallel_wavegan              : n=1,000  EER=  0.83%
  ljspeech_full_band_melgan          : n=1,000  EER= 30.60%
  ljspeech_hifiGAN                   : n=1,000  EER= 33.23%
  ljspeech_melgan                    : n=1,000  EER= 31.12%
  ljspeech_melgan_large              : n=1,000  EER

In [36]:
import json, os
from datetime import datetime

results_wf = {
    "phase": "Phase 5c — Supplementary Evaluation on WaveFake",
    "completed_at": datetime.now().isoformat(),
    "model_checkpoint": "/content/drive/MyDrive/deepfake_audio/checkpoints/stage2_best.pt",
    "model_dev_eer": 0.0069,
    "evaluation_dataset": {
        "name": "WaveFake (Frank et al., 2021) — sampled subset",
        "kaggle_source_spoof": "walimuhammadahmad/fakeaudio",
        "kaggle_source_bonafide": "mathurinache/the-lj-speech-dataset",
        "sampling_strategy": "Random sample of 1,500 LJSpeech bonafide + 1,000 spoof per vocoder × 9 vocoders",
        "utterances_total": 10500,
        "windows": 27483,
        "bonafide_count": 1500,
        "spoof_count": 9000,
        "vocoders": [
            "ljspeech_melgan", "ljspeech_melgan_large", "ljspeech_multi_band_melgan",
            "ljspeech_full_band_melgan", "ljspeech_parallel_wavegan",
            "ljspeech_waveglow", "ljspeech_hifiGAN",
            "jsut_multi_band_melgan", "jsut_parallel_wavegan"
        ],
    },
    "inference": {
        "batch_size": 16,
        "mixed_precision": True,
        "wall_clock_minutes": 7.9,
        "windows_per_second": 58,
        "note": "Slower windows/sec than ASVspoof because of resampling 22050/24000 → 16000",
    },
    "overall_results": {
        "eer": 0.2633,
        "auc": 0.8250,
        "accuracy": 0.7368,
        "threshold": 0.0000,
    },
    "cross_dataset_comparison": {
        "stage2_dev_2019_seen_attacks": 0.0069,
        "stage2_eval_2019_unseen_attacks": 0.0555,
        "stage2_eval_2021_unseen_attacks_plus_codecs": 0.0909,
        "stage2_eval_wavefake_novel_vocoders": 0.2633,
        "interpretation": "Largest cross-dataset gap. Model trained on ASVspoof attacks generalizes only weakly to standalone neural vocoder pipelines.",
    },
    "per_vocoder_eer": {
        "ljspeech_melgan": 0.3112,
        "ljspeech_melgan_large": 0.3385,
        "ljspeech_multi_band_melgan": 0.2192,
        "ljspeech_full_band_melgan": 0.3060,
        "ljspeech_parallel_wavegan": 0.2612,
        "ljspeech_waveglow": 0.2960,
        "ljspeech_hifiGAN": 0.3323,
        "jsut_multi_band_melgan": 0.0113,
        "jsut_parallel_wavegan": 0.0083,
    },
    "methodological_caveats": [
        "JSUT vocoder EERs (~1%) are likely inflated by domain shortcuts: bonafide is English LJSpeech, JSUT spoofs are Japanese audio at different sample rate (24 kHz vs 22 kHz). Model may be classifying language/speaker rather than detecting spoofing.",
        "The LJSpeech-based vocoder EERs (22-34%) are the methodologically meaningful results: same speaker, same content, same recording quality as bonafide; only the synthesis differs.",
        "High EERs on LJSpeech vocoders (mean 29.4%) reveal that ASVspoof-trained models generalize poorly to clean neural vocoder pipelines. This matches the original WaveFake paper's observations.",
        "Model has not been adapted to WaveFake — pure cross-dataset evaluation.",
    ],
    "key_findings": [
        "Cross-dataset robustness varies substantially by distribution shift type:",
        "  - Unseen attack types in same dataset: +4.86 pp (0.69% → 5.55%)",
        "  - Real-world codec degradation: +3.54 pp (5.55% → 9.09%)",
        "  - Novel vocoder pipelines on different domain: +17.24 pp (9.09% → 26.33%)",
        "Model has learned to detect ASVspoof-specific synthesis artifacts but not pure vocoder artifacts.",
        "Future work direction: include vocoder-only spoofing data during training to improve cross-dataset generalization.",
    ],
    "raw_scores_path": "/content/deepfake-audio-detection/results/scores/stage2_eval_wavefake.npz",
}

OUTPUT = '/content/deepfake-audio-detection/results/metrics/stage2_eval_wavefake_results.json'
os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
with open(OUTPUT, 'w') as f:
    json.dump(results_wf, f, indent=2)

print(f"Wrote {OUTPUT}")
print(f"Size: {os.path.getsize(OUTPUT)} bytes")

Wrote /content/deepfake-audio-detection/results/metrics/stage2_eval_wavefake_results.json
Size: 3479 bytes


In [37]:
from google.colab import userdata
import os

GITHUB_TOKEN = userdata.get('GITHUB_TOKEN')
os.chdir('/content/deepfake-audio-detection')

!git config user.email "95262824+Saracasm@users.noreply.github.com"
!git config user.name "Sara Iqbal"

!git add results/metrics/stage2_eval_wavefake_results.json
!git add results/scores/stage2_eval_wavefake.npz
!git status

!git commit -m "Phase 5c: WaveFake eval — 26.33% EER, reveals ASVspoof-specific overfitting"

push_url = f"https://Saracasm:{GITHUB_TOKEN}@github.com/Saracasm/deepfake-audio-detection.git"
!git push {push_url} main 2>&1 | grep -v {GITHUB_TOKEN}

On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   results/metrics/stage2_eval_wavefake_results.json
	new file:   results/scores/stage2_eval_wavefake.npz

[main 258c630] Phase 5c: WaveFake eval — 26.33% EER, reveals ASVspoof-specific overfitting
 2 files changed, 73 insertions(+)
 create mode 100644 results/metrics/stage2_eval_wavefake_results.json
 create mode 100644 results/scores/stage2_eval_wavefake.npz
To https://github.com/Saracasm/deepfake-audio-detection.git
   6b144b9..258c630  main -> main


We fine-tune Wav2Vec 2.0 for synthetic speech detection on ASVspoof 2019 LA and characterize its cross-dataset robustness across three distribution shift types: (1) unseen attacks in the original dataset (5.55% EER), (2) real-world codec degradation in ASVspoof 2021 LA (9.09% EER, matching the strongest published baselines), and (3) novel vocoder pipelines on a different domain (WaveFake, 26.33% EER). We show that fine-tuned Wav2Vec features generalize well to attack and codec variations but degrade significantly on out-of-distribution vocoder synthesis, suggesting the model has learned ASVspoof-specific synthesis artifacts rather than universal spoofing detection.

In [38]:
PREDICT_PY = '''"""
Inference module for deepfake audio detection.

Wraps the Stage 2 Wav2Vec 2.0 classifier with a clean public API.

Usage:
    from src.inference.predict import DeepfakeDetector
    detector = DeepfakeDetector(checkpoint_path="path/to/stage2_best.pt")
    result = detector.predict("path/to/audio.wav")
    print(result)
    # {"spoof_probability": 0.84, "prediction": "spoof", "confidence": 0.84,
    #  "utterance_duration_sec": 3.42, "n_windows": 1, "model_version": "stage2"}
"""

import os
from typing import Dict, Optional, Union
import torch
import torch.nn.functional as F
import numpy as np

from src.models.wav2vec_classifier import Wav2VecClassifier
from src.data.preprocessing import load_audio, segment_waveform, WINDOW_SAMPLES


# Default classifier threshold. 0.5 is naive; we tuned it during eval.
# Values closer to 0.5 = balanced; lower = more sensitive (more false alarms);
# higher = more conservative (more misses).
DEFAULT_THRESHOLD = 0.5


class DeepfakeDetector:
    """Anti-spoofing classifier wrapper for one-shot inference."""

    def __init__(
        self,
        checkpoint_path: str,
        device: Optional[str] = None,
        backbone_name: str = "facebook/wav2vec2-base",
        threshold: float = DEFAULT_THRESHOLD,
        use_mixed_precision: bool = True,
    ):
        """
        Args:
            checkpoint_path: path to a Stage 2 .pt checkpoint
            device: 'cuda', 'cpu', or None (auto-detect)
            backbone_name: HuggingFace model name for Wav2Vec backbone
            threshold: probability threshold above which we predict "spoof"
            use_mixed_precision: use fp16 inference (faster on GPU)
        """
        if device is None:
            device = "cuda" if torch.cuda.is_available() else "cpu"
        self.device = device
        self.threshold = threshold
        self.use_mixed_precision = use_mixed_precision and (device == "cuda")

        # Build model and load weights
        self.model = Wav2VecClassifier(
            backbone_name=backbone_name,
            num_classes=2,
            freeze_backbone=True,
        )
        ckpt = torch.load(checkpoint_path, map_location=device, weights_only=False)
        self.model.load_state_dict(ckpt["model_state_dict"])
        self.model = self.model.to(device)
        self.model.eval()

        # Store metadata for transparency
        self.checkpoint_metadata = {
            "epoch": ckpt.get("epoch"),
            "best_eer": ckpt.get("best_eer"),
            "checkpoint_path": checkpoint_path,
        }

    @torch.no_grad()
    def predict(
        self,
        audio_input: Union[str, torch.Tensor, np.ndarray],
        return_per_window: bool = False,
    ) -> Dict:
        """Predict bonafide vs spoof for a single audio input.

        Args:
            audio_input: either a file path (str), a 1-D Tensor at 16 kHz, or
                         a 1-D numpy array at 16 kHz.
            return_per_window: if True, include per-window probabilities in
                               the result for debugging.

        Returns:
            Dict with keys:
                spoof_probability: float in [0, 1]
                bonafide_probability: float in [0, 1]
                prediction: "bonafide" or "spoof"
                confidence: float in [0, 1] (probability of the predicted class)
                utterance_duration_sec: total audio length
                n_windows: number of 4-sec windows the audio was split into
                window_scores: (only if return_per_window=True) list of per-window spoof probs
        """
        # Step 1: Load and resample audio if needed
        if isinstance(audio_input, str):
            waveform = load_audio(audio_input)  # returns 1-D tensor at 16 kHz
        elif isinstance(audio_input, np.ndarray):
            waveform = torch.from_numpy(audio_input.astype(np.float32))
        elif isinstance(audio_input, torch.Tensor):
            waveform = audio_input.float()
            if waveform.dim() > 1:
                waveform = waveform.squeeze()
        else:
            raise ValueError(
                f"audio_input must be str, np.ndarray, or torch.Tensor; got {type(audio_input)}"
            )

        duration_sec = float(waveform.shape[0] / 16000)

        # Step 2: Segment into 4-sec windows
        windows = segment_waveform(waveform)  # list of 1-D tensors of length 64000
        n_windows = len(windows)

        # Step 3: Stack into a batch and run inference
        batch = torch.stack(windows, dim=0).to(self.device, non_blocking=True)

        if self.use_mixed_precision:
            with torch.amp.autocast(device_type="cuda", enabled=True):
                logits = self.model(batch)
        else:
            logits = self.model(batch)

        # Step 4: Compute per-window probabilities, then aggregate (mean)
        probs = torch.softmax(logits.float(), dim=-1).cpu().numpy()  # (n_windows, 2)
        window_spoof_probs = probs[:, 1].tolist()
        utt_spoof_prob = float(np.mean(window_spoof_probs))
        utt_bonafide_prob = 1.0 - utt_spoof_prob

        # Step 5: Apply threshold for hard prediction
        prediction = "spoof" if utt_spoof_prob > self.threshold else "bonafide"
        confidence = utt_spoof_prob if prediction == "spoof" else utt_bonafide_prob

        result = {
            "spoof_probability": utt_spoof_prob,
            "bonafide_probability": utt_bonafide_prob,
            "prediction": prediction,
            "confidence": confidence,
            "utterance_duration_sec": duration_sec,
            "n_windows": n_windows,
            "threshold_used": self.threshold,
        }
        if return_per_window:
            result["window_scores"] = window_spoof_probs
        return result

    def info(self) -> Dict:
        """Return metadata about this model checkpoint."""
        return {
            **self.checkpoint_metadata,
            "device": self.device,
            "threshold": self.threshold,
            "mixed_precision": self.use_mixed_precision,
        }
'''

PATH = '/content/deepfake-audio-detection/src/inference/predict.py'
import os
os.makedirs(os.path.dirname(PATH), exist_ok=True)

# Also create __init__.py for the module
init_path = '/content/deepfake-audio-detection/src/inference/__init__.py'
if not os.path.exists(init_path):
    open(init_path, 'w').close()

with open(PATH, 'w') as f:
    f.write(PREDICT_PY)

print(f"Wrote {PATH} ({len(PREDICT_PY)} bytes)")

Wrote /content/deepfake-audio-detection/src/inference/predict.py (6047 bytes)


In [40]:
import sys
sys.path.insert(0, '/content/deepfake-audio-detection')
from src.data.protocols import parse_all_partitions

LA_ROOT = '/content/kaggle_download/LA'
splits = parse_all_partitions(LA_ROOT)
print(f"Re-parsed:")
for name, utts in splits.items():
    n_bonafide = sum(1 for u in utts if u.label == 'bonafide')
    print(f"  {name}: {len(utts):,} (bonafide: {n_bonafide:,})")

Re-parsed:
  train: 25,380 (bonafide: 2,580)
  dev: 24,844 (bonafide: 2,548)
  eval: 71,237 (bonafide: 7,355)


In [41]:
import sys, importlib

# Reload modules
for mod in ['src.inference.predict']:
    if mod in sys.modules:
        importlib.reload(sys.modules[mod])
from src.inference.predict import DeepfakeDetector

# Build the detector once
print("Loading detector...")
CKPT = '/content/drive/MyDrive/deepfake_audio/checkpoints/stage2_best.pt'
detector = DeepfakeDetector(checkpoint_path=CKPT)
print(f"\nDetector loaded. Info:")
for k, v in detector.info().items():
    print(f"  {k}: {v}")

# Pick test samples from 2019 LA eval set
print("\n" + "=" * 70)
print("  TESTING ON REAL AUDIO")
print("=" * 70)

test_cases = []

# 1. Bonafide from 2019 eval
bonafide_eval = [u for u in splits['eval'] if u.label == 'bonafide']
test_cases.append(("2019 eval bonafide", bonafide_eval[0]))

# 2. Easy attack (A13)
attack_a13 = [u for u in splits['eval'] if u.attack_id == 'A13']
test_cases.append(("2019 eval spoof (A13, easy)", attack_a13[0]))

# 3. Hard attack (A10)
attack_a10 = [u for u in splits['eval'] if u.attack_id == 'A10']
test_cases.append(("2019 eval spoof (A10, hard)", attack_a10[0]))

# 4. Medium attack (A07)
attack_a07 = [u for u in splits['eval'] if u.attack_id == 'A07']
test_cases.append(("2019 eval spoof (A07, medium)", attack_a07[0]))

# 5. WaveFake spoof (LJSpeech-based, model struggles here)
import glob
wf_files = sorted(glob.glob('/content/wavefake/generated_audio/ljspeech_hifiGAN/*.wav'))
if wf_files:
    class _LightUtt:
        def __init__(self, path, uid):
            self.flac_path = path
            self.utterance_id = uid
            self.label = 'spoof'  # WaveFake is all spoof
    test_cases.append(("WaveFake spoof (HiFi-GAN)", _LightUtt(wf_files[0], 'wavefake_hifigan_0')))

# 6. Real LJSpeech (bonafide, but the model wasn't trained on this domain)
lj_files = sorted(glob.glob('/content/ljspeech/LJSpeech-1.1/wavs/*.wav'))
if lj_files:
    test_cases.append(("LJSpeech bonafide (out-of-domain)", _LightUtt(lj_files[0], 'lj_bonafide_0')))

# Run predictions
import time
for label, utt in test_cases:
    start = time.time()
    result = detector.predict(utt.flac_path)
    elapsed_ms = (time.time() - start) * 1000

    expected = utt.label
    actual = result['prediction']
    correct = "✓" if expected == actual else "✗"

    print(f"\n  [{label}]")
    print(f"    File: {utt.utterance_id}")
    print(f"    Expected: {expected}")
    print(f"    Predicted: {actual}  {correct}")
    print(f"    Spoof probability: {result['spoof_probability']:.4f}")
    print(f"    Confidence: {result['confidence']:.4f}")
    print(f"    Duration: {result['utterance_duration_sec']:.2f}s ({result['n_windows']} window{'s' if result['n_windows'] != 1 else ''})")
    print(f"    Inference time: {elapsed_ms:.0f}ms")

Loading detector...


Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

Wav2Vec2Model LOAD REPORT from: facebook/wav2vec2-base
Key                          | Status     |  | 
-----------------------------+------------+--+-
quantizer.weight_proj.weight | UNEXPECTED |  | 
project_q.weight             | UNEXPECTED |  | 
project_hid.weight           | UNEXPECTED |  | 
quantizer.codevectors        | UNEXPECTED |  | 
quantizer.weight_proj.bias   | UNEXPECTED |  | 
project_hid.bias             | UNEXPECTED |  | 
project_q.bias               | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.



Detector loaded. Info:
  epoch: 9
  best_eer: 0.006940865275480051
  checkpoint_path: /content/drive/MyDrive/deepfake_audio/checkpoints/stage2_best.pt
  device: cuda
  threshold: 0.5
  mixed_precision: True

  TESTING ON REAL AUDIO

  [2019 eval bonafide]
    File: LA_E_5849185
    Expected: bonafide
    Predicted: bonafide  ✓
    Spoof probability: 0.0000
    Confidence: 1.0000
    Duration: 4.39s (2 windows)
    Inference time: 240ms

  [2019 eval spoof (A13, easy)]
    File: LA_E_5932896
    Expected: spoof
    Predicted: spoof  ✓
    Spoof probability: 1.0000
    Confidence: 1.0000
    Duration: 5.80s (2 windows)
    Inference time: 73ms

  [2019 eval spoof (A10, hard)]
    File: LA_E_8339197
    Expected: spoof
    Predicted: bonafide  ✗
    Spoof probability: 0.0001
    Confidence: 0.9999
    Duration: 1.46s (1 window)
    Inference time: 93ms

  [2019 eval spoof (A07, medium)]
    File: LA_E_8844552
    Expected: spoof
    Predicted: spoof  ✓
    Spoof probability: 0.6621
    C

In [42]:
from google.colab import userdata
import os

GITHUB_TOKEN = userdata.get('GITHUB_TOKEN')
os.chdir('/content/deepfake-audio-detection')

!git config user.email "95262824+Saracasm@users.noreply.github.com"
!git config user.name "Sara Iqbal"

!git add src/inference/__init__.py src/inference/predict.py
!git status
!git commit -m "Phase 6: add production inference module (DeepfakeDetector wrapper)"

push_url = f"https://Saracasm:{GITHUB_TOKEN}@github.com/Saracasm/deepfake-audio-detection.git"
!git push {push_url} main 2>&1 | grep -v {GITHUB_TOKEN}

On branch main
Your branch is ahead of 'origin/main' by 2 commits.
  (use "git push" to publish your local commits)

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   src/inference/__init__.py
	new file:   src/inference/predict.py

[main 0e975e7] Phase 6: add production inference module (DeepfakeDetector wrapper)
 2 files changed, 157 insertions(+)
 create mode 100644 src/inference/__init__.py
 create mode 100644 src/inference/predict.py
To https://github.com/Saracasm/deepfake-audio-detection.git
   258c630..0e975e7  main -> main
